#pragma once

// GameRender public headers — include this from client projects
#include "Camera.h"
#include "CategoryRenderers.h"
#include "CmoLoader.h"
#include "ConstantBufferAllocator.h"
#include "DdsLoader.h"
#include "FlatColorPipeline.h"
#include "GpuResourceManager.h"
#include "LandscapeTexture.h"
#include "Mesh.h"
#include "MeshCache.h"
#include "PipelineHelpers.h"
#include "PostProcess.h"
#include "ShaderVisibleHeap.h"
#include "SpaceObjectRenderer.h"
#include "SpriteBatch.h"
#include "Starfield.h"
#include "SurfaceRenderer.h"
#include "TacticalGrid.h"
#include "UploadHeap.h"
#include "VertexColorPipeline.h"
